version: '3.8'

services:
  seata-server:
    image: seataio/seata-server:1.8.0
    container_name: seata-server
    ports:
      - "8091:8091"
      - "7091:7091"
    environment:
      - SEATA_PORT=8091
      - STORE_MODE=db
    volumes:
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/localtime"
      - "/usr/share/zoneinfo/Asia/Shanghai:/etc/timezone"
      - ./seata-server/resources/application.yml:/seata-server/resources/application.yml
    networks:
      - nexus-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

networks:
  nexus-network:
    driver: bridge 